address:
  city: TJ
  street: XiangYangLu
  zipcode: 11111111

app:
  name: jack
  age: 30
  email: jack@123.com
  address:
    city: BJ
    street: ChaoYang
    zipcode: 123456

#数组
names:
  - jackson
  - lucy
  - lili

#List集合
products:
  - name: 西瓜
    price: 3.0
  - name: 苹果
    price: 2.0

#Map集合
vips:
  vip1:
    name: 张三
    age: 20
  vip2:
    name: 李四
    age: 22

spring:
  profiles:
    active: prod
